/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-12-16 02:05:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.animalConnect.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class proJoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/eclipse/spring/workspace3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/animalConnect/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/eclipse/spring/workspace3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/animalConnect/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1606779483606L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<!--\r\n");
      out.write("\tTactile by Pixelarity\r\n");
      out.write("\tpixelarity.com | hello@pixelarity.com\r\n");
      out.write("\tLicense: pixelarity.com/license\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Untitled</title>\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=1\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/resources/assets/css/main.css\" />\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Main -->\r\n");
      out.write("<article id=\"main\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\t<h2 class=\"major special\" align=\"center\">전문가 Sing Up</h2>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Elements -->\r\n");
      out.write("\t\t\t<div class=\"row gtr-200\">\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-12-medium\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"table-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"/animalConnect/member/proJoin\" name=\"proJoinForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box\" style=\"flaot:left; width:500px; text-align:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom:25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"check\" id=\"check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t \t <label for=\"check\"><strong><a href=\"terms.html\">이용약관</a> 및 개인정보수집 동의</strong></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"NO\" name=\"proCheck\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom:25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>닉네임</label>             \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"nicName\" style=\"line-height:100px;\" placeholder=\"NicName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p id=\"idCheck_text\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom:25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>이름</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"proName\" style=\"line-height:100px;\" placeholder=\"Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom:25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>이메일</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"proEmail\" style=\"line-height:100px;\" placeholder=\"Email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom:25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>비밀번호<sub>(특수문자 포함 8글자 이상)</sub></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"proPw\" style=\"line-height:100px;\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom:25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>비밀번호 확인</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"proCheckPw\" style=\"line-height:100px;\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom:25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>전화번호<sub>('-' 없이 입력)</sub></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"proHp\" style=\"line-height:100px;\" placeholder=\"H.P\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom:25px;\" id=\"newText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>활동 가능주소</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"sido1\" id=\"sido1\" style=\"display:inline; width:220px;\">\r\n");
      out.write("     \t\t\t\t\t\t\t\t\t<option value=\"\">시/도</option>\r\n");
      out.write("   \t\t\t\t\t\t\t\t \t</select>\r\n");
      out.write("    \t\t\t\t\t\t\t\t<select name=\"gugun1\" id=\"gugun1\"  style=\"display:inline; width:220px;\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t<option value=\"\">군/구</option>\r\n");
      out.write("    \t\t\t\t\t\t\t\t</select>\r\n");
      out.write("    \t\t\t\t\t\t\t\t<input id=\"map\" type=\"button\" value=\"등록\" onclick=\"checkMap(sido1.value, gugun1.value)\" style=\"margin-top: 20px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"maps\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t<label style=\"text-align:left;\">자격증 및 경력 증명서<sub>(필수)</sub></label>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"alt\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" style=\"width:55%;\" name=\"file1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" onclick=\"cancleFile('file1')\" value=\"첨부 삭제\" style=\"margin-left:100px; padding:0px; height:40px;\"/>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" style=\"width:55%;\" name=\"file2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" onclick=\"cancleFile('file2')\" value=\"첨부 삭제\" style=\"margin-left:100px; padding:0px; height:40px;\"/>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" style=\"width:55%;\" name=\"file3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" onclick=\"cancleFile('file3')\" value=\"첨부 삭제\" style=\"margin-left:100px; padding:0px; height:40px;\"/>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-bottom:25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" onclick=\"formSubmit()\" value=\"확인\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer/footer.jsp", out, false);
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<script>var contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";</script>\r\n");
      out.write("\t\t\t<script src=\"/resources/assets/js/proJoin.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\tfunction cancleFile(fileTagName){\r\n");
      out.write("\t\t\t\t\tif($.browser.msie){\t//ie일 때 초기화\r\n");
      out.write("\t\t\t\t\t\t$(\"input[name='\"+ fileTagName +\"']\").replaceWith($(\"input[name='\"+ fileTagName +\"']\").clone(true));\r\n");
      out.write("\t\t\t\t\t}else{ //그 외 브라우저일 때 초기화\r\n");
      out.write("\t\t\t\t\t\t$(\"input[name='\"+ fileTagName +\"']\").val(\"\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
