CREATE SEQUENCE SEQ_NOTICE;

INSERT INTO NOTICE  VALUES 
(SEQ_NOTICE.NEXTVAL, '더미 제목 5','더미 내용 5',SYSDATE,'alpha@naver.com',0)


SELECT * FROM users;

SELECT *  FROM PRO;

SELECT * FROM ADMIN;

SELECT * FROM MAP;

ALTER  "MAP" 
SET PROMAPS = '경상북도 의성군' 
WHERE PROMAPS = NULL ;

INSERT INTO "MAP" VALUES  ('gold77@naver.com','전라북도 군산시');
INSERT INTO "MAP" (PROEMAIL)
(SELECT PROEMAIL FROM PRO);
INSERT INTO "MAP" VALUES  ('iron88@naver.com','전라북도 군산시');
INSERT INTO pro(PRONAME,PROEMAIL,PROPW,PROHP,NICNAME,PROCHECK) 
VALUES('김동욱','good@naver.com','2222@!', '010-8412-7709','닉1','YES');